b.dr = function (dr) {
	alert('b.dr')
	if (U(dr)) {
		return this.direction
	}
	this.direction = dr;
	return this
} 
b.dir = function (d) {
	alert('b.dir')
	var b = this
	if (U(d)) {
		return b._dir
	}
	b._dir = d
	return b
}
function arcade() {// Hit testing the screen width, otherwise our sprite would disappear //
// We've reached the right side of our screen
// We need to walk left now to go back to our initial position
//sS.addFlipped(true, false, false)
// walk_h has been generated by addFlippedFrames and
// contained the right facing animations
//T.f(40)
//sprite.shadow = new createjs.Shadow("#454", 10, 15, 14)
//spriteUrl = "/assets/sprites/metalslug_mummy37x45.png"
//sprite always assumed to start facing right (and flipping it horizontqlly is the left)
// - so i must draw facing right
////}
}